server:
  port: 9090

spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
      routes:
        - id: service
          uri: http://localhost:9091/
          predicates:
            - Path=/service/**
          filters:
            - name: PreFilter
            - name: PostFilter